# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: spotifest-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  environment: ${env:}

functions:
  # party functions
  create:
    description: Create a party 
    handler: handler.create
    events: 
      - http:
          path: party/create
          method: post
  join:
    description: Join a party
    handler: handler.join
    events: 
      - http:
          path: party/join
          method: post
  get: 
    description: Get a party
    handler: handler.get
    events: 
      - http: 
          path: party/get
          method: get
  
  # Spotify functions
  auth:
    description: Authenticate with Spotify
    handler: handler.auth
    events: 
      - http:
          path: spotify/auth
          method: get
  refresh: 
    description: Refresh spotify access token
    handler: handler.refresh
    events: 
      - http:
          path: spotify/refresh
          method: post
      
