# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: spotifest-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  environment: ${env:}

functions:
  hello:
    description: Say hello
    handler: handler.hello
    events:
      - http:
         path: functions/hello
         method: get
  create:
    description: Create a party 
    handler: handler.create
    events: 
      - http:
          path: party/create
          method: post
  auth:
    description: Authenticate with Spotify
    handler: handler.auth
    events: 
      - http:
          path: spotify/auth
          method: get
      
